name: CICD for Laravel 

on:
  push:
    branches:
      - main

jobs:
  run-backend-on-ec2:
    name: Deploy backend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.2]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Laravel ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: SSH to instance
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |

          echo "$PRIVATE_KEY" > "$HOME/my-ssh-key.pem"
          chmod 600 /home/runner/my-ssh-key.pem
          ssh -o StrictHostKeyChecking=no -i "$HOME/my-ssh-key.pem" "$USER_NAME@$HOSTNAME" '
              cd /home/ubuntu/ &&
              rm -rf unnati-backend &&
              git clone https://github.com/Sahil1384/unnati-backend.git &&
              cd /home/ubuntu/unnati-backend &&
              echo "Installing Dependencies" &&
              composer install --no-interaction --optimize-autoloader --no-dev &&
              php artisan key:generate &&
              php artisan optimize:clear &&
              php artisan cache:clear &&
              php artisan route:cache &&
              php artisan route:clear &&
              php artisan view:clear &&
              php artisan config:cache &&
              php artisan db:seed &&
              sudo chmod -R 775 /home/ubuntu/unnati-backend &&
              sudo chown -R unnati:root /home/ubuntu/unnati-backend
          '
